"""B group: RLR audio backend via habitat-sim AudioSensor (档 ① swap-in).

We import habitat_sim only to reach the RLR audio bindings. We do NOT
render anything from Habitat here — the video comes from A group's UE
render pass. Per-frame we:

  1. Move each audio source (for example dog_golden or dog_beagle_v2) to
     its current xyz
  2. Call sim.get_sensor_observations()["audio"] to get the RIR (FOA 4ch)
  3. Convolve dry source audio with the RIR to get the wet contribution
     for that source at that frame's timestamp
  4. Overlap-add wet frames into a per-source output buffer

Then mix the two sources and write a 4ch WAV.

Coordinate frame note: Habitat uses right-handed Y-up. Habitat's GLB loader
imports our Z-up GLBs as (x, z, -y), so scene-space source/listener positions
must use the same transform. See `_habitat_from_scene()` below.

CLI:
    python run_audio_pass_rlr.py \
        --spec ../../data/shoebox_v2_spec.json \
        --mesh ../../tmp/spike_rlr/shoebox_v2_mesh.glb \
        --materials ../../tmp/spike_rlr/shoebox_v2_materials.json \
        --out ../../tmp/spike_output/raw_audio/audio_B_rlr_FOA.wav
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
import soundfile as sf

TOOLS_ROOT = Path(__file__).resolve().parents[1]
if str(TOOLS_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOLS_ROOT))

from audio_event_schedule import prepare_animal_call
from animal_audio import (
    is_animal_tag,
    is_synthetic_audio_path,
    resolve_animal_audio_path,
)
from speech_audio import is_speech_lookup, resolve_speech_audio_path
from source_trajectory import acoustic_trajectory


REPO_ROOT = Path(__file__).resolve().parents[2]
RLR_NATIVE_BINAURAL_CHANNEL_ORDER = (0, 1)


# --- coordinate transform ---------------------------------------------------
# SSOT coord frame: right-handed Z-up meters, +Y = apartment/window direction.
# Habitat coord frame: right-handed Y-up meters. Habitat's GLB importer maps
# our GLB coordinates to (x, z, -y), which is visible in pathfinder bounds:
# an SSOT y range [a,b] appears as Habitat z range [-b,-a]. Keep source and
# listener positions in that same frame, or RLR will mirror them into the
# wrong acoustic space.

def _habitat_from_scene(pos_scene):
    """Map SSOT (x, y_forward, z_up) -> Habitat (x, z_up, -y_forward).

    This matches Habitat's GLB loader for the acoustic meshes generated by
    gen_mesh.py and gen_mesh_apartment.py. The minus sign on scene Y is not a
    convention preference; without it, apartment sources are mirrored across
    the listener and can land on a disconnected RLR/navmesh island.
    """
    x, y, z = pos_scene
    return np.array([x, z, -y], dtype=np.float32)


def _make_rlr_materials_json(materials_sidecar, out_path):
    """Convert our per-triangle material JSON to a SoundSpaces-style JSON
    that setAudioMaterialsJSON can read.

    Our sidecar format:
      {"materials": [{"name": tag, "alpha": [b1..b4], "scattering": s, "transmission": [t1..t4]}, ...]}

    Sound-Spaces format:
      {"materials": [{"name": ..., "absorption": [freq1, val1, freq2, val2, ...], "scattering": [...], "transmission": [...], "labels": [...]}, ...]}
    """
    # 4 bands center frequencies (SoundSpaces high-quality preset default)
    bands_hz = [125.0, 500.0, 2000.0, 8000.0]

    def interleave(vals):
        return [v for pair in zip(bands_hz, vals) for v in pair]

    out = {"materials": []}
    for m in materials_sidecar["materials"]:
        out["materials"].append({
            "name": m["name"],
            "absorption": interleave(m["alpha"]),
            "scattering": interleave([m["scattering"]] * 4),
            "transmission": interleave(m["transmission"]),
            "labels": [m["name"]],
        })

    with open(out_path, "w") as f:
        json.dump(out, f, indent=2)
    return out_path


def _load_scene_and_scene_two_dogs(spec_path=None):
    """Local import guard + spec-version dispatch.

    - spec_version == "v2" (shoebox_v2): compose_two_dog_scene_v2
    - spec_version == "apartment_v1":    compose_two_dog_scene_apartment

    If spec_path is None (legacy callers), assume shoebox v2.
    """
    sys.path.insert(0, str(REPO_ROOT / "tools" / "spike_rlr"))
    if spec_path is None:
        from scene_two_dogs_v2 import compose_two_dog_scene_v2
        return compose_two_dog_scene_v2
    with open(spec_path) as f:
        version = json.load(f).get("spec_version", "v2")
    if version == "apartment_v1":
        from scene_two_dogs_apartment import compose_two_dog_scene_apartment
        return compose_two_dog_scene_apartment
    # default: shoebox_v2 (spec_version=="v2")
    from scene_two_dogs_v2 import compose_two_dog_scene_v2
    return compose_two_dog_scene_v2


# Override map: for review spikes we override registered tags with hand-picked
# real animal clips. Synthetic sentinels are still supported when a spec asks
# for them explicitly, but no production animal tag should silently map to one.
_TAG_AUDIO_OVERRIDES = {
    # Golden: real dog bark (restored per user request)
    "dog_golden": "/data/datasets/omniaudio/train-data-az-360-large/Barking Aldi Dog_358.wav",
    # Beagle review asset: same real dog bark class as golden.
    "dog_beagle_v2": "/data/datasets/omniaudio/train-data-az-360-large/Barking Aldi Dog_358.wav",
    # British shorthair review asset: local Omniloc cat purring clip.
    "cat_british_shorthair_v2": "/data/datasets/cy/omniloc/train/audio/cat purring/-A1eKkZVSRw_000070.mp3",
}


def _synth_pink_noise(sample_rate, duration_s, seed=0):
    """Synthesize pink (1/f) noise. Flat perceptual spectrum, fully stationary."""
    n = int(round(sample_rate * duration_s))
    rng = np.random.default_rng(seed)
    # Voss-McCartney approximation: sum of N halved-rate white noise generators
    n_octaves = 16
    y = np.zeros(n, dtype=np.float32)
    for k in range(n_octaves):
        step = 1 << k
        if step >= n:
            break
        white = rng.standard_normal(n // step + 1).astype(np.float32)
        # Repeat each sample `step` times, then crop to n
        expanded = np.repeat(white, step)[:n]
        y += expanded
    y = y / max(np.abs(y).max(), 1e-9)
    y = y * 0.5  # peak = 0.5 so headroom stays sane after conv
    return y.astype(np.float32)


def _synth_click_train(sample_rate, duration_s, click_hz=4.0, click_ms=10.0):
    """Repeating short pulse. Between clicks the RIR tail is audible in
    isolation, so any per-frame IR change (occlusion, moving source) shows
    up in the perceived reverb between clicks -- much clearer to hear than
    a continuous source where late-reverb accumulates and masks direct-sound
    variation.

    click_hz: pulses per second.
    click_ms: width of each pulse (Hanning-windowed).
    """
    n = int(round(sample_rate * duration_s))
    y = np.zeros(n, dtype=np.float32)
    click_len = max(int(round(sample_rate * click_ms / 1000)), 2)
    click = np.hanning(click_len).astype(np.float32) * 0.9
    period_samples = int(round(sample_rate / click_hz))
    for start in range(0, n, period_samples):
        end = min(start + click_len, n)
        y[start:end] += click[:end - start]
    return y


def _synth_piano_scale(sample_rate, duration_s, base_hz=261.63,
                        note_period_s=0.6, harmonics=8, amp=0.35,
                        sustain_s=1.8):
    """Synthesize a legato C-major piano scale (do-re-mi-fa-sol-la-si-do…).

    Each note's tail (~1.8s exponential decay, sustain-pedal-style) continues
    past the next attack, so successive notes overlap — no silent gaps.
    Sequence wraps back to lower octaves after C5 so we always fill the
    full clip regardless of duration.

    Signal characteristics:
      * Piano-like additive harmonics with mild inharmonicity
      * Fast (5ms) attack, slow (~2s) exponential decay -> legato/sustain
      * Rich content up to ~2-4 kHz (harmonics of 260-520 Hz fundamentals)
        -> strong HRTF ILD cues for spatial demo
    """
    # C major scale semitones from C4 (repeats up an octave for longer clips)
    scale = [0, 2, 4, 5, 7, 9, 11, 12, 14, 16, 17, 19, 21, 23, 24]
    n_total = int(round(sample_rate * duration_s))
    n_notes = int(np.ceil(duration_s / note_period_s))
    period_n = int(round(note_period_s * sample_rate))
    sustain_n = int(round(sustain_s * sample_rate))
    y = np.zeros(n_total + sustain_n, dtype=np.float32)  # extra room for tails

    for i in range(n_notes):
        step = scale[i % len(scale)]
        f0 = base_hz * (2.0 ** (step / 12.0))
        start = i * period_n
        t = np.arange(sustain_n, dtype=np.float32) / sample_rate
        note = np.zeros(sustain_n, dtype=np.float32)
        for h in range(1, harmonics + 1):
            f_h = f0 * h * (1.0 + 0.0004 * h * h)
            a_h = (1.0 / (h ** 1.2)) * np.exp(-0.05 * h)
            note += a_h * np.sin(2 * np.pi * f_h * t)
        # Slow exponential decay (sustain pedal style)
        env = np.exp(-1.8 * t / sustain_s)
        # 5ms attack ramp
        attack_n = int(0.005 * sample_rate)
        env[:attack_n] *= np.linspace(0, 1, attack_n)
        note *= env
        end = start + sustain_n
        y[start:end] += note.astype(np.float32)

    y = y[:n_total]
    y = y / (np.max(np.abs(y)) + 1e-9) * amp
    return y.astype(np.float32)


def _synth_hf_tone(sample_rate, duration_s, base_hz=2000.0, vibrato_hz=6.0,
                    vibrato_cents=40.0, amp=0.5):
    """Steady high-frequency tone (2kHz) with mild vibrato.

    Why high frequency for the spike:
      * Sofa fabric α_8kHz = 0.60 vs α_125Hz = 0.15 -> 4x stronger occlusion
        drop on high freqs (drop is fully spatial, not source-timevariant)
      * Human ITD/ILD azimuth resolution is best in the 1.5-5 kHz band,
        so L/R movement is easier to hear
      * Vibrato (~40 cent, 6 Hz) keeps the ear "hooked" on the tone without
        adding intrinsic amplitude/spectrum motion
    Purpose: any amplitude/timbre change you hear is caused by RLR
    spatial propagation, not the source waveform.
    """
    n = int(round(sample_rate * duration_s))
    t = np.arange(n, dtype=np.float32) / sample_rate
    # Vibrato: cents -> ratio -> instantaneous frequency
    vib_ratio = np.exp(np.log(2) / 1200.0 * vibrato_cents *
                        np.sin(2 * np.pi * vibrato_hz * t))
    inst_hz = base_hz * vib_ratio
    # Integrate instantaneous frequency to get phase
    phase = 2 * np.pi * np.cumsum(inst_hz) / sample_rate
    y = amp * np.sin(phase).astype(np.float32)
    return y


def _load_dry_source(
    tag,
    sample_rate,
    duration_s,
    seed=42,
    source_spec=None,
    schedule_metadata_out=None,
):
    """Load a dry source wav for a given tag.

    Source spec audio_path/audio_lookup wins, then _TAG_AUDIO_OVERRIDES, then
    audio_registry, then a synthesized placeholder. Synthetic sentinel strings
    are still supported when explicitly requested.
    """
    n_samples = int(round(sample_rate * duration_s))
    is_speech_source = False
    manual_repeat_applied = False
    try:
        source_spec = source_spec or {}
        if source_spec.get("mute_audio") or source_spec.get("audio_lookup") == "silent":
            print(f"[audio] {tag}: muted by source spec")
            if schedule_metadata_out is not None:
                schedule_metadata_out.update(
                    {"schema": "animal_audio_event_schedule_v1", "mode": "muted", "event_count": 0}
                )
            return np.zeros(n_samples, dtype=np.float32)
        override = None
        explicit_path = source_spec.get("audio_path") or source_spec.get("dry_audio_path")
        audio_lookup = source_spec.get("audio_lookup")
        if explicit_path and is_synthetic_audio_path(explicit_path):
            override = str(explicit_path)
        elif audio_lookup and is_speech_lookup(audio_lookup):
            is_speech_source = True
            speech_kwargs = {
                "explicit_path": explicit_path,
                "root": source_spec.get("speech_root"),
            }
            if source_spec.get("speech_speaker_gender") is not None:
                speech_kwargs["speaker_gender"] = source_spec["speech_speaker_gender"]
            wav_path = str(resolve_speech_audio_path(audio_lookup, **speech_kwargs))
            print(f"[audio] {tag}: using speech lookup {audio_lookup} -> {os.path.basename(wav_path)}")
        elif explicit_path:
            wav_path = str(resolve_animal_audio_path(
                tag,
                audio_lookup=audio_lookup,
                explicit_path=explicit_path,
            ))
            print(f"[audio] {tag}: using spec audio_path {os.path.basename(wav_path)}")
        elif audio_lookup:
            wav_path = str(resolve_animal_audio_path(tag, audio_lookup=audio_lookup))
            print(f"[audio] {tag}: using spec audio_lookup {audio_lookup} -> {os.path.basename(wav_path)}")
        else:
            override = _TAG_AUDIO_OVERRIDES.get(tag)
        if override == "__pink_noise__":
            print(f"[audio] {tag}: using SYNTHETIC pink noise (steady-state)")
            return _synth_pink_noise(sample_rate, duration_s, seed=seed)
        if override == "__click_train__":
            print(f"[audio] {tag}: using SYNTHETIC click train (4Hz, 10ms pulses)")
            return _synth_click_train(sample_rate, duration_s,
                                       click_hz=4.0, click_ms=10.0)
        if override == "__hf_tone__":
            print(f"[audio] {tag}: using SYNTHETIC 2kHz vibrato tone (steady HF)")
            return _synth_hf_tone(sample_rate, duration_s,
                                   base_hz=2000.0, vibrato_hz=6.0,
                                   vibrato_cents=40.0, amp=0.5)
        if override == "__piano_scale__":
            print(f"[audio] {tag}: using SYNTHETIC piano C-major scale (do-re-mi)")
            return _synth_piano_scale(sample_rate, duration_s)
        if override and os.path.exists(override):
            wav_path = override
            print(f"[audio] {tag}: using SPIKE OVERRIDE {os.path.basename(wav_path)}")
        elif "wav_path" not in locals():
            sys.path.insert(0, str(REPO_ROOT / "tools"))
            from gpurir_scenes.audio_registry import pick_audio
            picked = pick_audio(tag, np.random.default_rng(seed))
            # pick_audio returns (path, source, keyword) or just path (varies by
            # registry version). Support both.
            wav_path = picked[0] if isinstance(picked, tuple) else picked
            print(f"[audio] {tag}: using registry pick {os.path.basename(wav_path)}")
        y, sr = sf.read(wav_path, dtype="float32")
        if y.ndim > 1:
            y = y.mean(axis=1)
        if sr != sample_rate:
            # simple linear resample (crude but good enough for spike)
            new_len = int(round(len(y) * sample_rate / sr))
            y = np.interp(np.linspace(0, len(y), new_len, endpoint=False),
                          np.arange(len(y)), y).astype(np.float32)
        clip_start_s = source_spec.get("audio_clip_start_s")
        clip_duration_s = source_spec.get("audio_clip_duration_s")
        repeat_interval_s = source_spec.get("audio_repeat_interval_s")
        if clip_start_s is not None or clip_duration_s is not None:
            start = max(0, int(round(float(clip_start_s or 0.0) * sample_rate)))
            if clip_duration_s is None:
                end = len(y)
            else:
                end = start + max(1, int(round(float(clip_duration_s) * sample_rate)))
            segment = y[start:min(end, len(y))]
            if len(segment) == 0:
                raise ValueError(
                    f"empty audio clip for {tag}: start={clip_start_s}, "
                    f"duration={clip_duration_s}, len={len(y) / sample_rate:.3f}s"
                )
            if repeat_interval_s is not None:
                repeated = np.zeros(n_samples, dtype=np.float32)
                step = max(
                    len(segment),
                    int(round(float(repeat_interval_s) * sample_rate)),
                )
                for start_idx in range(0, n_samples, step):
                    end_idx = min(start_idx + len(segment), n_samples)
                    repeated[start_idx:end_idx] += segment[:end_idx - start_idx]
                y = repeated
                manual_repeat_applied = True
            else:
                y = segment
        adaptive_repeat = bool(source_spec.get("adaptive_repeat_short_calls", True))
        if (
            is_animal_tag(tag)
            and not is_speech_source
            and not manual_repeat_applied
            and adaptive_repeat
        ):
            y, schedule = prepare_animal_call(
                y,
                sample_rate=sample_rate,
                duration_s=duration_s,
                rng=np.random.default_rng(seed),
            )
            schedule.update(
                {
                    "tag": tag,
                    "audio_path": str(wav_path),
                    "adaptive_repeat_short_calls": True,
                }
            )
        else:
            # Speech and explicitly scheduled sources are never seamless-looped.
            fixed = np.zeros(n_samples, dtype=np.float32)
            event_start_s = float(source_spec.get("audio_event_start_s", 0.0))
            if not np.isfinite(event_start_s) or event_start_s < 0.0:
                raise ValueError(f"invalid audio_event_start_s for {tag}: {event_start_s}")
            event_start_sample = min(
                n_samples,
                int(round(event_start_s * sample_rate)),
            )
            copy_samples = min(len(y), n_samples - event_start_sample)
            fixed[
                event_start_sample : event_start_sample + copy_samples
            ] = y[:copy_samples]
            y = fixed
            schedule = {
                "schema": "animal_audio_event_schedule_v1",
                "tag": tag,
                "audio_path": str(wav_path),
                "mode": (
                    "manual_repeat_interval"
                    if manual_repeat_applied
                    else "single_clip_silence_padded"
                ),
                "event_count": None if manual_repeat_applied else 1,
                "adaptive_repeat_short_calls": False,
                "is_speech_source": bool(is_speech_source),
                "target_duration_s": float(duration_s),
                "events": [
                    {
                        "index": 0,
                        "start_sample": event_start_sample,
                        "end_sample": event_start_sample + copy_samples,
                        "start_s": event_start_sample / sample_rate,
                        "end_s": (event_start_sample + copy_samples) / sample_rate,
                    }
                ],
            }
        if schedule_metadata_out is not None:
            schedule_metadata_out.update(schedule)
        # Peak normalize to prevent clipping in convolution
        peak = np.abs(y).max()
        if peak > 1e-9:
            y = y * (0.8 / peak)
        return y
    except Exception as e:
        if (source_spec or {}).get("strict_audio"):
            raise RuntimeError(f"strict audio source {tag} failed: {e}") from e
        # Fallback: use a bark-like AM sinusoid (obvious placeholder)
        print(f"[audio] WARNING: audio_registry failed for {tag}: {e}. Using placeholder tone.")
        t = np.linspace(0, duration_s, n_samples, endpoint=False, dtype=np.float32)
        # Different F0 per tag so B/C tests can distinguish; envelope repeats
        base_hz = 300.0 if "husky" in tag else 800.0
        env = np.abs(np.sin(2 * np.pi * 3 * t))  # 3 barks/sec
        y = 0.5 * env * np.sin(2 * np.pi * base_hz * t).astype(np.float32)
        return y


def _write_source_schedule_manifest(out_wav_path, schedules):
    path = Path(out_wav_path).with_name(
        Path(out_wav_path).stem + "_source_schedule.json"
    )
    path.write_text(
        json.dumps(
            {
                "schema": "rlr_audio_source_schedules_v1",
                "sources": schedules,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return path


def build_rlr_sim(glb_path, materials_json_path, sample_rate=16000,
                  channel_layout="ambisonics", indirect_ray_count=500):
    """Create a Habitat Simulator with a single AudioSensor.

    No visual sensors, no physics -- audio only. The scene mesh comes from
    our SSOT-generated shoebox_v2_mesh.glb.
    """
    # Imported lazily so dispatcher/help tests can import this module in
    # spear-env; actual RLR rendering still requires the ss2 env.
    import habitat_sim
    from habitat_sim.sensor import RLRAudioPropagationChannelLayoutType

    sim_cfg = habitat_sim.SimulatorConfiguration()
    sim_cfg.scene_id = str(glb_path)
    sim_cfg.enable_physics = False
    # Audio-only: skip the OpenGL renderer entirely (avoids the "cannot
    # retrieve OpenGL version" error when running headless without X). RLR
    # doesn't need a GL context — it operates on the loaded mesh directly.
    sim_cfg.create_renderer = False
    sim_cfg.load_semantic_mesh = False
    sim_cfg.requires_textures = False

    # Minimal agent (required by habitat, but we don't use it for locomotion)
    agent_cfg = habitat_sim.AgentConfiguration()

    audio_spec = habitat_sim.AudioSensorSpec()
    # Habitat's Simulator.get_sensor_observations hardcodes the uuid
    # 'audio_sensor' when dispatching to _get_audio_observation(); if we
    # rename we lose the routing. Stick to what the sim expects.
    audio_spec.uuid = "audio_sensor"
    # AudioSensorSpec defaults to [0, 1.5, 0] relative to the agent. Our spec
    # mic position is already the listener position, so clear the local offset.
    audio_spec.position = [0.0, 0.0, 0.0]
    audio_spec.enableMaterials = False  # we'll set via JSON to override GLB PBR
    if channel_layout == "ambisonics":
        audio_spec.channelLayout.type = RLRAudioPropagationChannelLayoutType.Ambisonics
        audio_spec.channelLayout.channelCount = 4  # 1st-order FOA
    elif channel_layout == "binaural":
        audio_spec.channelLayout.type = RLRAudioPropagationChannelLayoutType.Binaural
        audio_spec.channelLayout.channelCount = 2
    else:
        raise ValueError(f"unknown channel layout {channel_layout}")

    audio_spec.acousticsConfig.sampleRate = sample_rate
    audio_spec.acousticsConfig.threadCount = 4
    audio_spec.acousticsConfig.direct = True
    audio_spec.acousticsConfig.indirect = True
    audio_spec.acousticsConfig.diffraction = True
    audio_spec.acousticsConfig.transmission = True
    audio_spec.acousticsConfig.temporalCoherence = True
    audio_spec.acousticsConfig.indirectRayCount = indirect_ray_count
    audio_spec.acousticsConfig.sourceRayCount = 200
    audio_spec.acousticsConfig.indirectRayDepth = 50
    audio_spec.acousticsConfig.frequencyBands = 4
    audio_spec.acousticsConfig.unitScale = 1.0  # meters

    # sensor mounted on the agent
    agent_cfg.sensor_specifications = [audio_spec]

    cfg = habitat_sim.Configuration(sim_cfg, [agent_cfg])
    sim = habitat_sim.Simulator(cfg)

    # Load material overrides
    audio_sensor = sim.get_agent(0)._sensors["audio_sensor"]
    audio_sensor.setAudioMaterialsJSON(str(materials_json_path))

    return sim, audio_sensor


def _mic_yaw_deg_from_spec(spec: dict) -> float:
    """Return the listener yaw in the SSOT scene frame.

    Apartment Plan-2 specs put yaw on spec["mic"]. Older shoebox specs only
    carried it on camera_configs[0]. Their canonical view0 faces +Y, i.e. 90
    deg in the SSOT +X-forward convention.
    """
    mic = spec.get("mic", {})
    if "yaw_deg" in mic:
        return float(mic["yaw_deg"])
    cameras = spec.get("camera_configs") or []
    if cameras and "yaw_deg" in cameras[0]:
        return float(cameras[0]["yaw_deg"])
    return 90.0


def _habitat_agent_yaw_deg_for_scene_yaw_deg(scene_yaw_deg: float) -> float:
    """Convert SSOT scene yaw to Habitat agent yaw about Habitat +Y(up).

    SSOT yaw=0 faces +X_scene; yaw=90 faces +Y_scene. After the GLB-matching
    _habitat_from_scene transform, scene forward becomes
    (cos(yaw), 0, -sin(yaw)) in Habitat coordinates. Habitat agent forward is
    local -Z, so rotating it by (yaw - 90) degrees around +Y points the
    listener at the SSOT forward.
    """
    return float((float(scene_yaw_deg) - 90.0) % 360.0)


def _set_agent_pose(sim, mic_pos_scene, mic_yaw_deg: float = 90.0):
    """Place the Habitat agent (mic/listener) at mic_pos and face mic_yaw.

    Habitat convention: agent's "forward" is -Z_habitat (like a camera looking
    down its -Z axis). Our SSOT yaw=0 faces +X_scene; positive yaw rotates
    CCW in XY. After the GLB-matching transform in _habitat_from_scene, scene
    forward maps to (cos(yaw), 0, -sin(yaw)) in Habitat.

    This orientation matters because RLR's ambisonic output is expressed in
    the LISTENER's local frame (not world frame). Leaving it fixed at +Y_scene
    makes random-yaw review clips sound left/right by world axes instead of by
    the rendered camera view.
    """
    import quaternion  # noqa: E402  (bundled with habitat-sim)
    agent = sim.get_agent(0)
    state = agent.get_state()
    state.position = _habitat_from_scene(mic_pos_scene)
    agent_yaw = np.deg2rad(_habitat_agent_yaw_deg_for_scene_yaw_deg(mic_yaw_deg))
    half = agent_yaw / 2.0
    state.rotation = np.quaternion(float(np.cos(half)), 0.0,
                                   float(np.sin(half)), 0.0)
    agent.set_state(state)


def compute_rir_and_render(spec_path, glb_path, materials_sidecar_path,
                           out_wav_path, downmix_stereo_path=None,
                           quality_mode="high", verbose=True):
    """End-to-end: build sim, iterate trajectory, convolve, mix, write."""
    with open(spec_path) as f:
        spec = json.load(f)
    with open(materials_sidecar_path) as f:
        materials_sidecar = json.load(f)

    sample_rate = spec["audio_config"]["sample_rate_hz"]
    duration_s = spec["audio_config"]["duration_s"]
    n_frames = spec["render_config"]["n_frames"]
    fps = spec["render_config"]["fps"]
    n_samples_total = int(round(sample_rate * duration_s))
    samples_per_frame = int(round(sample_rate / fps))

    # Build the SoundSpaces-formatted materials json in a sibling temp file
    rlr_materials_json = Path(materials_sidecar_path).with_name(
        Path(materials_sidecar_path).stem + "_rlr.json"
    )
    _make_rlr_materials_json(materials_sidecar, rlr_materials_json)
    if verbose:
        print(f"[rlr] materials JSON -> {rlr_materials_json}")

    # Quality mode -> ray count (must be set on spec, not on live sensor)
    ray_count_by_quality = {"low": 100, "high": 500, "max": 5000}
    indirect_ray_count = ray_count_by_quality.get(quality_mode, 500)

    sim, audio_sensor = build_rlr_sim(
        glb_path, rlr_materials_json,
        sample_rate=sample_rate,
        indirect_ray_count=indirect_ray_count,
    )

    # Compose scene to get trajectories (dispatch by spec_version)
    load_scene = _load_scene_and_scene_two_dogs(spec_path)
    scene = load_scene(spec_path)
    source_specs_by_tag = {
        src.get("tag"): src for src in spec.get("sources", []) if src.get("tag")
    }

    # Place mic (Habitat's agent = the listener)
    _set_agent_pose(sim, spec["mic"]["pos_m"], _mic_yaw_deg_from_spec(spec))

    # Wet output buffer (n_channels x n_samples_total). We know from
    # build_rlr_sim we set 4-ch ambisonic; assert to be defensive.
    n_channels = 4  # 1st-order FOA
    wet = np.zeros((n_channels, n_samples_total), dtype=np.float32)
    per_source_wet_map = {}  # tag -> (n_channels, n_samples) FOA buffer
    source_schedules = {}

    # Function-scope wall clock start so 0-source clips can still return
    # {"wall_time_s": ...} without UnboundLocalError. Overwritten below per
    # source if any exists.
    t0 = time.time()

    # For each source: precompute dry, then per-frame get IR + convolve
    for a in scene.animals:
        tag = a.tag
        source_spec = source_specs_by_tag.get(tag) or {}
        if source_spec.get("mute_audio") or source_spec.get("audio_lookup") == "silent":
            print(f"[rlr] source {tag}: muted, skipping RIR/audio render")
            continue
        traj_scene = acoustic_trajectory(a.trajectory_m, source_spec)
        schedule_metadata = {}
        dry = _load_dry_source(
            tag,
            sample_rate,
            duration_s,
            source_spec=source_spec,
            schedule_metadata_out=schedule_metadata,
        )
        source_schedules[tag] = schedule_metadata
        if verbose:
            print(f"[rlr] source {tag}: dry rms = {np.sqrt(np.mean(dry**2)):.4f}, "
                  f"peak = {np.max(np.abs(dry)):.4f}")

        per_source_wet = np.zeros_like(wet)
        t0 = time.time()

        for f in range(n_frames):
            src_pos = traj_scene[f]
            src_hab = _habitat_from_scene(src_pos)
            audio_sensor.setAudioSourceTransform(src_hab)

            obs = sim.get_sensor_observations()
            ir_raw = obs["audio_sensor"]  # list-of-arrays (per channel) or ndarray
            # Normalize to (n_channels, n_samples_ir) ndarray
            if isinstance(ir_raw, list):
                ir = np.asarray(ir_raw, dtype=np.float32)
            else:
                ir = np.asarray(ir_raw, dtype=np.float32)
            if ir.ndim == 2 and ir.shape[0] > ir.shape[1]:
                ir = ir.T  # ensure (n_channels, n_samples_ir)
            elif ir.ndim == 1:
                ir = ir[None, :]  # (1, n_samples)

            # convolve the audio around this frame with the IR, add into per_source_wet
            frame_start = f * samples_per_frame
            frame_end = min(frame_start + samples_per_frame, n_samples_total)
            dry_chunk = dry[frame_start:frame_end]
            if len(dry_chunk) == 0:
                continue
            # naive conv per channel; result length = len(dry_chunk) + ir.shape[1] - 1
            for c in range(n_channels):
                wet_chunk = np.convolve(dry_chunk, ir[c], mode="full")
                w_end = min(frame_start + len(wet_chunk), n_samples_total)
                per_source_wet[c, frame_start:w_end] += wet_chunk[:w_end - frame_start]

            if verbose and f % 15 == 0:
                print(f"[rlr] {tag}: frame {f}/{n_frames} "
                      f"src={src_pos} ir_shape={ir.shape} "
                      f"elapsed={time.time() - t0:.1f}s")

        wet += per_source_wet
        per_source_wet_map[tag] = per_source_wet.copy()

    # Write per-source (solo) FOA + stereo BEFORE the shared peak-norm so
    # each solo track has its own natural loudness. Using a common global
    # normalizer would drown out husky in the mixed track once occluded.
    out_wav_path = Path(out_wav_path)
    out_wav_path.parent.mkdir(parents=True, exist_ok=True)

    def _write_stereo(foa_buf, path):
        """FOA(4, N) -> stereo(N, 2) via ch3 L/R decode. See below for details."""
        W_ch = foa_buf[0]
        lr_axis = foa_buf[3]
        L = W_ch - 0.707 * lr_axis
        R = W_ch + 0.707 * lr_axis
        st = np.stack([L, R], axis=1)
        p = np.abs(st).max()
        if p > 1e-9:
            st = st * (0.9 / p)
        sf.write(str(path), st, sample_rate, subtype="PCM_16")

    for tag, buf in per_source_wet_map.items():
        solo_peak = np.abs(buf).max()
        buf_norm = buf * (0.9 / solo_peak) if solo_peak > 1e-9 else buf
        solo_foa = out_wav_path.parent / f"{out_wav_path.stem}_{tag}_FOA.wav"
        solo_stereo = out_wav_path.parent / f"{out_wav_path.stem}_{tag}_stereo.wav"
        sf.write(str(solo_foa), buf_norm.T, sample_rate, subtype="PCM_16")
        _write_stereo(buf_norm, solo_stereo)
        print(f"[rlr] wrote SOLO {solo_foa.name} + {solo_stereo.name}")

    # Peak normalize the mixed buffer
    peak = np.abs(wet).max()
    if peak > 1e-9:
        wet = wet * (0.9 / peak)

    # Write 4-channel FOA wav (mixed)
    sf.write(str(out_wav_path), wet.T, sample_rate, subtype="PCM_16")
    print(f"[rlr] wrote {out_wav_path}  shape={wet.shape}  sr={sample_rate}")
    schedule_path = _write_source_schedule_manifest(out_wav_path, source_schedules)
    print(f"[rlr] wrote source schedules {schedule_path}")

    # FOA -> stereo downmix.
    # RLR outputs 1st-order ambisonics but empirically the channel that
    # correlates with source azimuth (left/right of listener) is channel 3
    # for our shoebox scene, not channel 1 as ACN would predict. This is
    # likely FuMa-style ordering [W, X, Y, Z] where the sensor's local
    # X-axis maps to left/right when the agent is yawed 180 about world Y.
    #
    # Sign was also inverted vs my initial guess: agent right ↔ world -X,
    # so wet[3] > 0 when source is at world +X (mic's L side). We flip so
    # world +X hits R channel and world -X hits L (matches "画面右 = 世界
    # +X" convention documented in pipeline_zh.md appendix A).
    if downmix_stereo_path and n_channels == 4:
        W = wet[0]
        # LR axis (empirically ch3; see comment above)
        lr_axis = wet[3]
        # Positive lr_axis correlates with world +X (right in the SPEAR
        # picture-right = world+X = right ear convention).
        L = W - 0.707 * lr_axis   # world -X (left) louder in L
        R = W + 0.707 * lr_axis   # world +X (right) louder in R
        stereo = np.stack([L, R], axis=1)
        peak = np.abs(stereo).max()
        if peak > 1e-9:
            stereo = stereo * (0.9 / peak)
        sf.write(str(downmix_stereo_path), stereo, sample_rate, subtype="PCM_16")
        print(f"[rlr] wrote stereo downmix {downmix_stereo_path}")

    return {"wall_time_s": time.time() - t0}


def compute_binaural(spec_path, glb_path, materials_sidecar_path,
                      out_wav_path, quality_mode="high", verbose=True):
    """RLR native binaural (2ch) rendering. Uses the AudioSensor's built-in
    HRTF decoder. Same trajectory + per-source overlap-add as FOA path.

    With the GLB-matching scene->Habitat transform `(x, z, -y)`, RLR's native
    binaural output is already ordered [left, right]. Keep the explicit channel
    order constant above so future calibration changes are localized.
    """
    with open(spec_path) as f:
        spec = json.load(f)
    with open(materials_sidecar_path) as f:
        materials_sidecar = json.load(f)

    sample_rate = spec["audio_config"]["sample_rate_hz"]
    duration_s = spec["audio_config"]["duration_s"]
    n_frames = spec["render_config"]["n_frames"]
    fps = spec["render_config"]["fps"]
    n_samples_total = int(round(sample_rate * duration_s))
    samples_per_frame = int(round(sample_rate / fps))

    rlr_materials_json = Path(materials_sidecar_path).with_name(
        Path(materials_sidecar_path).stem + "_rlr.json")
    _make_rlr_materials_json(materials_sidecar, rlr_materials_json)

    ray_count_by_quality = {"low": 100, "high": 500, "max": 5000}
    indirect_ray_count = ray_count_by_quality.get(quality_mode, 500)

    sim, audio_sensor = build_rlr_sim(
        glb_path, rlr_materials_json,
        sample_rate=sample_rate,
        channel_layout="binaural",
        indirect_ray_count=indirect_ray_count,
    )

    load_scene = _load_scene_and_scene_two_dogs(spec_path)
    scene = load_scene(spec_path)
    source_specs_by_tag = {
        src.get("tag"): src for src in spec.get("sources", []) if src.get("tag")
    }
    _set_agent_pose(sim, spec["mic"]["pos_m"], _mic_yaw_deg_from_spec(spec))

    wet = np.zeros((2, n_samples_total), dtype=np.float32)
    per_source_wet_map = {}
    source_schedules = {}

    for a in scene.animals:
        tag = a.tag
        source_spec = source_specs_by_tag.get(tag) or {}
        if source_spec.get("mute_audio") or source_spec.get("audio_lookup") == "silent":
            print(f"[rlr-bin] source {tag}: muted, skipping RIR/audio render")
            continue
        traj_scene = acoustic_trajectory(a.trajectory_m, source_spec)
        schedule_metadata = {}
        dry = _load_dry_source(
            tag,
            sample_rate,
            duration_s,
            source_spec=source_spec,
            schedule_metadata_out=schedule_metadata,
        )
        source_schedules[tag] = schedule_metadata
        if verbose:
            print(f"[rlr-bin] source {tag}: dry rms={np.sqrt(np.mean(dry**2)):.4f}")
        per_source_wet = np.zeros_like(wet)
        t0 = time.time()

        for f in range(n_frames):
            src_pos = traj_scene[f]
            src_hab = _habitat_from_scene(src_pos)
            audio_sensor.setAudioSourceTransform(src_hab)
            obs = sim.get_sensor_observations()
            ir_raw = obs["audio_sensor"]
            ir = np.asarray(ir_raw, dtype=np.float32)
            if ir.ndim == 2 and ir.shape[0] > ir.shape[1]:
                ir = ir.T
            elif ir.ndim == 1:
                ir = ir[None, :]

            frame_start = f * samples_per_frame
            frame_end = min(frame_start + samples_per_frame, n_samples_total)
            dry_chunk = dry[frame_start:frame_end]
            if len(dry_chunk) == 0:
                continue
            for c in range(2):
                wet_chunk = np.convolve(dry_chunk, ir[c], mode="full")
                w_end = min(frame_start + len(wet_chunk), n_samples_total)
                per_source_wet[c, frame_start:w_end] += wet_chunk[:w_end - frame_start]

            if verbose and f % 25 == 0:
                print(f"[rlr-bin] {tag}: frame {f}/{n_frames} elapsed={time.time()-t0:.1f}s")

        wet += per_source_wet
        per_source_wet_map[tag] = per_source_wet.copy()

    channel_order = list(RLR_NATIVE_BINAURAL_CHANNEL_ORDER)
    wet = wet[channel_order, :]

    out_wav_path = Path(out_wav_path)
    out_wav_path.parent.mkdir(parents=True, exist_ok=True)
    for tag, buf in per_source_wet_map.items():
        buf_sw = buf[channel_order, :]
        p = np.abs(buf_sw).max()
        if p > 1e-9:
            buf_sw = buf_sw * (0.9 / p)
        solo_path = out_wav_path.parent / f"{out_wav_path.stem}_{tag}_binaural.wav"
        sf.write(str(solo_path), buf_sw.T, sample_rate, subtype="PCM_16")
        print(f"[rlr-bin] wrote SOLO {solo_path.name}")

    peak = np.abs(wet).max()
    if peak > 1e-9:
        wet = wet * (0.9 / peak)
    sf.write(str(out_wav_path), wet.T, sample_rate, subtype="PCM_16")
    print(f"[rlr-bin] wrote {out_wav_path} shape={wet.shape} sr={sample_rate}")
    schedule_path = _write_source_schedule_manifest(out_wav_path, source_schedules)
    print(f"[rlr-bin] wrote source schedules {schedule_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default=str(REPO_ROOT / "data" / "shoebox_v2_spec.json"))
    ap.add_argument("--mesh", default=str(REPO_ROOT / "tmp" / "spike_rlr" / "shoebox_v2_mesh.glb"))
    ap.add_argument("--materials", default=str(REPO_ROOT / "tmp" / "spike_rlr" / "shoebox_v2_materials.json"))
    ap.add_argument("--out", default=str(REPO_ROOT / "tmp" / "spike_output" / "raw_audio" / "audio_B_rlr_FOA.wav"))
    ap.add_argument("--stereo-out", default=str(REPO_ROOT / "tmp" / "spike_output" / "raw_audio" / "audio_B_rlr_stereo.wav"))
    ap.add_argument("--quality", default="high", choices=["low", "high", "max"])
    ap.add_argument("--channel-layout", default="ambisonics",
                    choices=["ambisonics", "binaural"],
                    help="ambisonics=4ch FOA output (default); binaural=2ch native binaural output")
    args = ap.parse_args()

    t_start = time.time()

    # Level-1/Level-2 profiling: wrap the RLR audio pass in a StageTimer.
    # clip_id is derived from spec basename (e.g. apartment_v1_000). CSV
    # goes to <out-dir>/profile_per_clip.csv where out-dir is inferred from
    # the --out argument's parent-parent (…/tmp/spike_output_apartment/raw_audio_hq/foo.wav
    # -> …/tmp/spike_output_apartment/).
    spec_stem = Path(args.spec).stem  # e.g. "apartment_v1_spec"
    clip_id = spec_stem.replace("_spec", "") + "_000"
    csv_path = Path(args.out).resolve().parent.parent / "profile_per_clip.csv"
    stage_name = "rlr_audio_binaural" if args.channel_layout == "binaural" else "rlr_audio_foa"

    sys.path.insert(0, str(REPO_ROOT / "tools" / "spike_rlr"))
    from profiling import StageTimer

    with StageTimer(stage_name, clip_id=clip_id, csv_path=csv_path):
        if args.channel_layout == "binaural":
            # Reuse the same --out path (caller controls filename) but call the
            # binaural code path. --stereo-out is unused in this mode.
            compute_binaural(
                spec_path=args.spec,
                glb_path=args.mesh,
                materials_sidecar_path=args.materials,
                out_wav_path=Path(args.out),
                quality_mode=args.quality,
            )
        else:
            compute_rir_and_render(
                spec_path=args.spec,
                glb_path=args.mesh,
                materials_sidecar_path=args.materials,
                out_wav_path=args.out,
                downmix_stereo_path=args.stereo_out,
                quality_mode=args.quality,
            )
    print(f"[rlr] TOTAL wall time: {time.time() - t_start:.1f}s")


if __name__ == "__main__":
    main()
